### ISSUE TITLE
Panics with 'slice index starts at 4 but ends at 0' in `solve_linear_program`

### ISSUE THREAD

**Issue by Elabajaba** [andriyDev/dodgy#8] opened 2023-08-08 07:41 UTC
I'm running into a seemingly random panic when trying to use dodgy, and I'm not quite sure how to investigate it (currently my program just spawns a bunch of units onto a big square navmesh and has them path to random destinations, using dodgy for local collision avoidance, and it crashes after anywhere from a couple seconds to a minute).

```
panicked at 'slice index starts at 4 but ends at 0', C:\Users\elabajaba\.cargo\registry\src\index.crates.io-6f17d22bba15001f\dodgy-1.2.1\src\linear_programming.rs:299:33
```

Relevant lines from the backtrace:
```
   4: dodgy::linear_programming::solve_linear_program
   5: dodgy::Agent::compute_avoiding_velocity
```

Dodgy call (I'll add a link to the repo tomorrow, need to clean it up a bit first):

```
let avoidance_velocity = dodgy_agent.agent.compute_avoiding_velocity(
    &dodgy_neighbours,
    &obstacles,
    dodgy_agent.agent.velocity,
    time.delta_seconds(),
    &AvoidanceOptions {
        obstacle_margin: 0.1,
        time_horizon: 1.0,
        obstacle_time_horizon: 0.5,
    },
);
```

**Comment by andriyDev** [comment] 2023-08-08 15:23
I'm betting if you were running in debug mode, we'd hit [this}(https://github.com/andriyDev/dodgy/blob/58dd2885be49933a650d4000b4463eecf7ca42b2/src/linear_programming.rs#L262C65-L262C65) assert (in fact maybe it should just be an assert).

It still _should not_ be possible to get tripped though. The only thing I can think of is that your obstacles are in the wrong order (not CW), but presumably those edges should get filtered out anyway. Maybe somehow one slips through and invalidates all velocities causing this error.

Since this is a boundary, you want the order of vertices to be the OPPOSITE of what you normally do. That is, if a solid box goes CCW, a hollow box (e.g. a boundary) goes CW. To be honest, it's been a while since I've worked on this stuff, so I don't remember whether it is CW or CCW for normal obstacles.

**Comment by Elabajaba** [comment] 2023-08-08 21:40
> Since this is a boundary, you want the order of vertices to be the OPPOSITE of what you normally do. That is, if a solid box goes CCW, a hollow box (e.g. a boundary) goes CW. To be honest, it's been a while since I've worked on this stuff, so I don't remember whether it is CW or CCW for normal obstacles.

The test arena I'm using doesn't have any obstacles other than a boundary box around the edges (and it's in the correct order). It could be that units are escaping and that's causing the crash, but previously when I'd gotten the winding order wrong for obstacles it wouldn't crash, units would just all end up clustering onto a couple different lines.

> (P.S. consider using landmass and bevy_landmass. They're far from finished but should handle all the movement stuff for you. No pressure though haha, this crate is intended to be used by anyone!)

This originally started off as me wanting to compare the pathfinding performance of [`bevy_pathmesh`](https://lib.rs/crates/bevy_pathmesh) and [`OxidizedNavigation`](https://lib.rs/crates/oxidized_navigation), but I've somehow ended up working on a runtime navmesh generator for bevy_pathmesh, adding new collider backends for oxidized_navigation, and trying to get nice unit movement. I'll add `bevy_landmass` to the list of pathfinding solutions to compare if I ever get around to actually writing any benchmarks.

**Comment by andriyDev** [comment] 2023-08-10 01:59
Hmmm that's concerning. I'll try to make a little test of my own of just filling up a box with agents and see what I come up with.

> This originally started off as me wanting to compare the pathfinding performance of [`bevy_pathmesh`](https://lib.rs/crates/bevy_pathmesh) and [`OxidizedNavigation`](https://lib.rs/crates/oxidized_navigation), but I've somehow ended up working on a runtime navmesh generator for bevy_pathmesh, adding new collider backends for oxidized_navigation, and trying to get nice unit movement. I'll add `bevy_landmass` to the list of pathfinding solutions to compare if I ever get around to actually writing any benchmarks.

Oooooh that would be interesting to see how `landmass` compares to the others! Although I still haven't done a lot of work on the performance side of things - I'm more focused on getting feature complete first.

**Comment by andriyDev** [comment] 2023-08-10 03:04
Ok I tried just taking a box and filling it with agents and I didn't get any issues even after everything was slowing to a crawl.

One thing I've noticed about your setup is that you're using the agent's velocity as it's preferred velocity. I don't see how that could cause a panic though... More info about your setup would be helpful!

**Comment by Elabajaba** [comment] 2023-08-22 03:37
Sorry I didn't get back to you sooner, I just revisited this and now it isn't crashing...

**Comment by andriyDev** [comment] 2023-08-22 04:50
LMAO hmm still a little concerning but it's hard to fix this without a reproducible setup :/ I'm gonna close this for now. If it happens again, feel free to reopen!

**Closed by andriyDev** 2023-08-22 04:50 UTC
